"""LUNA SuperSpeed device on the gw_usb3 PHY — Gowin DK_USB (GW5AT-60).

The fully open USB3 Gen1 stack: LUNA's LTSSM/link/protocol/endpoint layers
drive our Amaranth GTR12 soft PHY through the width=8 PIPE adapter -- no
vendor controller netlists anywhere in the build.

    [gowin-serdes]   GTR12 Quad 0 lane 1, CPLL, 200 MHz refclk forward,
                     **5G boot trim** (Gen1-only; pclk = 125 MHz from
                     power-on, no rate change ever needed).
    [gw_usb3]        Usb31Phy(gen2=False, rate_init=0) behind
                     luna.gateware.interface.serdes_phy.GowinGTR12PIPE.
    [LUNA]           USBSuperSpeedDevice + standard control endpoint,
                     descriptors 1209:0001 (pid.codes test PID).
    [debug]          uart 0 (/dev/ttyUSB4): link-event probe;
                     uart 1 (/dev/ttyUSB5): clock/symbol probe.
                     LED = link trained (U0).

Simulation heritage: the same adapter+PHY pair passes the LFPS smoke sim
and the full raw-symbol training sim to U0
(luna/examples/usb/superspeed/gowin_gtr12_*.py).

NOTE on the CSR blob: this example boots the SerDes in the 5G trim, so
serdes.toml/serdes.csr generated here deliberately DIFFER from the
byte-pinned 10G reference configuration used by usb31-enum.

Build & program:

    python top.py                # build only (build/)
    python top.py serdes         # regenerate serdes.toml/csr only
    python top.py flash          # flash the existing bitstream
    python top.py program        # build + flash

Watch:  stty -F /dev/ttyUSB4 115200 raw -echo; cat /dev/ttyUSB4
"""

import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# luna (this fork), gw_usb3 and gowin_serdes are installed packages
# (fork venv: `pdm install` at the repo root).  No sys.path reaches.

from amaranth.hdl import *
from amaranth.lib.cdc import FFSynchronizer

from gowin_serdes.dkusb_gw5at60 import DKUSBGW5AT60Platform, add_serdes_refclk_forward

from gowin_serdes import GowinDevice, make_usb3_serdes, usb3_boot_writes
from gowin_serdes.config import RefClkSource
from gowin_serdes.usb3 import attach_usb3_phy

from luna.gateware.interface.serdes_phy.gowin_gtr12 import GowinGTR12PIPE
from luna.gateware.usb.usb3.device import USBSuperSpeedDevice

from usb_protocol.emitters import SuperSpeedDeviceDescriptorCollection

from gowin_serdes.bench import ClockFreqProbe

# ── Configuration ─────────────────────────────────────────────────────
QUAD, LANE = 0, 1
REF_CLK_SOURCE = RefClkSource.Q0_REFCLK1
REF_CLK_FREQ = "200M"
DBG_FREQ = 24_000_000
BAUD_RATE = 115_200


# SerDes boot trim.  "10G" = the byte-pinned reference blob; the PIPE
# adapter then performs the hardware-proven 10G->5G rate-change sequence
# itself before reporting the PHY ready (boot_rate_switch).  The direct
# "5G" boot blob is generated by an untested path and produced a
# host-invisible TX on first hardware trial (LFPS fine, TS bursts
# unanswered) -- kept selectable for future trim debugging.
BOOT_RATE = "10G"


def make_serdes():
    return make_usb3_serdes(GowinDevice.GW5AT_60, QUAD, LANE,
                            REF_CLK_SOURCE, REF_CLK_FREQ,
                            boot_rate=BOOT_RATE)


def create_descriptors():
    descriptors = SuperSpeedDeviceDescriptorCollection()

    with descriptors.DeviceDescriptor() as d:
        d.idVendor           = 0x1209       # pid.codes
        d.idProduct          = 0x0001       # test PID
        d.bcdUSB             = 3.2
        d.bMaxPacketSize0    = 9            # 2**9 = 512
        d.iManufacturer      = "LUNA + gw_usb3"
        d.iProduct           = "GTR12 SuperSpeed bring-up"
        d.iSerialNumber      = "DK60"
        d.bNumConfigurations = 1

    with descriptors.ConfigurationDescriptor() as c:
        c.bMaxPower = 50
        with c.InterfaceDescriptor() as i:
            i.bInterfaceNumber = 0

    return descriptors


class LunaEnumTop(Elaboratable):
    def elaborate(self, platform):
        m = Module()

        led = platform.request("led", 0)
        usb_pwr_en = platform.request("usb_pwr_en", 0)
        m.d.comb += usb_pwr_en.o.eq(0)     # device mode: never source VBUS

        # Quiet the USB2 pins (see usb31-enum: floating pins make the
        # host see a phantom low-speed device and power-cycle the port).
        usb2 = platform.request("usb2_softphy", 0)
        m.d.comb += [
            usb2.pullup_en.o.eq(0),
            usb2.term_dp.o.eq(0),
            usb2.term_dn.o.eq(0),
            usb2.tx_dp.o.eq(0),
            usb2.tx_dn.o.eq(0),
            usb2.dp.oe.eq(0),
            usb2.dp_b.oe.eq(0),
            usb2.dn.oe.eq(0),
            usb2.dn_b.oe.eq(0),
        ]

        # ==============================================================
        # Clocks & power-on reset (vendor-proven ordering)
        # ==============================================================
        sys_clk = add_serdes_refclk_forward(m, platform)
        m.domains += ClockDomain("cfg", reset_less=True)
        m.d.comb += ClockSignal("cfg").eq(sys_clk)

        clk24 = platform.request("clk_24m", 0)
        m.domains += ClockDomain("dbg", reset_less=True)
        m.d.comb += ClockSignal("dbg").eq(clk24.i)

        # POR: quad POR at ~330 us, LUNA+PHY released LAST at ~1.3 ms.
        # Releasing logic before the quad leaves POR loses the CSR
        # sequencer's init writes (hard-won usb31-enum lesson).
        por_cnt = Signal(18)
        por_n = Signal()
        luna_go = Signal()
        with m.If(~por_cnt.all()):
            m.d.cfg += por_cnt.eq(por_cnt + 1)

        # Board key = full POR replay (LTSSM restart without reflash).
        key = platform.request("key", 0)
        key_s = Signal(2)
        m.d.cfg += key_s.eq(Cat(key.i, key_s[0]))
        with m.If(key_s[1]):
            m.d.cfg += por_cnt.eq(0)

        m.d.cfg += [
            por_n.eq(por_cnt > 66_000),
            luna_go.eq(por_cnt.all()),
        ]

        # ==============================================================
        # SerDes + PHY + PIPE adapter
        # ==============================================================
        serdes, group = make_serdes()
        m.submodules.serdes = serdes
        lane = group.lanes[0]
        drp = getattr(serdes, group.drp_name)
        m.d.comb += serdes.por_n.eq(por_n)

        # Bug #38 (see luna-multiep/top.py): plumb the lane into the PHY's
        # CSR sequencer; the adapter default is Q0_LN1 regardless of QUAD/
        # LANE.  Elaboration-identical for the shipping Q0_LN1 config.
        from gw_usb3.upar_csr import UparCsrConfig
        adapter = GowinGTR12PIPE(boot_rate_switch=(BOOT_RATE == "10G"),
                                 boot_domain="ss_raw",
                                 phy_kwargs=dict(
                                     csr_config=UparCsrConfig(quad=QUAD,
                                                              lane=LANE)))
        m.submodules.adapter = adapter
        attach_usb3_phy(m, adapter.phy, lane, drp)

        # ss/sync domains: pclk (125 MHz, 5G trim) with the POR-released
        # reset, synchronized in a raw pclk domain.
        m.domains += ClockDomain("ss_raw", reset_less=True)
        m.d.comb += ClockSignal("ss_raw").eq(lane.tx.pcs_clkout)
        rstn_r0 = Signal()
        rstn_r1 = Signal()
        # LUNA's ss/sync reset is released only once the adapter reports
        # the boot rate switch COMPLETE (phy_ready): no LUNA state ever
        # clocks at the 156.25 MHz boot rate or through the rate-change
        # pclk retune (boot-window corruption class; HANDOVER 10k).  The
        # adapter sequences the bring-up itself in the reset-free ss_raw
        # domain, started by the POR chain.
        m.d.comb += adapter.boot_start.eq(luna_go)
        m.d.ss_raw += [rstn_r0.eq(luna_go & adapter.phy_ready),
                       rstn_r1.eq(rstn_r0)]
        for dom in ("ss", "sync"):
            m.domains += ClockDomain(dom)
            m.d.comb += [
                ClockSignal(dom).eq(ClockSignal("ss_raw")),
                ResetSignal(dom).eq(~rstn_r1),
            ]

        # ==============================================================
        # LUNA SuperSpeed device
        # ==============================================================
        m.submodules.usb = usb = USBSuperSpeedDevice(
            phy=adapter, sync_frequency=125e6)
        usb.add_standard_control_endpoint(create_descriptors())

        m.d.comb += led.o.eq(usb.link_trained)

        # ==============================================================
        # Debug UARTs
        # ==============================================================
        # PIPE-level symbol counters ("ss" domain).
        rx_com = Signal()
        tx_com = Signal()
        rx_d102 = Signal()
        tx_d102 = Signal()
        m.d.comb += [
            rx_com.eq(adapter.rx_datavalid & adapter.rx_datak[0]
                      & (adapter.rx_data[0:8] == 0xBC)),
            tx_com.eq(~adapter.tx_elec_idle & adapter.tx_datak[0]
                      & (adapter.tx_data[0:8] == 0xBC)),
            rx_d102.eq(adapter.rx_datavalid & (adapter.rx_datak[0:4] == 0)
                       & (adapter.rx_data[0:16] == 0x4A4A)),
            tx_d102.eq(~adapter.tx_elec_idle & (adapter.tx_datak[0:4] == 0)
                       & (adapter.tx_data[0:16] == 0x4A4A)),
        ]

        # uart 0: link-event probe.
        # C <ss-freq> <lfps_det> <ts1_det> <ts2_det> <rx_com> <flag>
        uart0 = platform.request("uart", 0)
        m.submodules.linkprobe = linkprobe = DomainRenamer({"cfg": "dbg"})(
            ClockFreqProbe(clk_freq=DBG_FREQ, baud=BAUD_RATE, channels=(
                ("ss", None),
                ("ss", usb.debug_lfps_polling_detected),
                ("ss", usb.debug_ts1_detected),
                ("ss", usb.debug_ts2_detected),
                ("ss", rx_com),
            )))
        link_flags = Signal(4)
        m.submodules += FFSynchronizer(
            Cat(usb.link_trained, usb.link_in_reset,
                usb.debug_phy_ready, usb.debug_engage_terminations),
            link_flags, o_domain="dbg")
        m.d.comb += [
            linkprobe.flags.eq(link_flags),
            uart0.tx.o.eq(linkprobe.tx_o),
        ]
        rx0_unused = Signal()
        m.submodules += FFSynchronizer(uart0.rx.i, rx0_unused,
                                       o_domain="dbg")

        # uart 1: clock/symbol probe.
        # C <pclk> <rxclk> <upar> <rx_d102> <tx_d102> <flag>
        uart1 = platform.request("uart", 1)
        m.domains += ClockDomain("rxprobe", reset_less=True)
        m.d.comb += ClockSignal("rxprobe").eq(lane.rx.pcs_clkout)
        m.domains += ClockDomain("uparprobe", reset_less=True)
        m.d.comb += ClockSignal("uparprobe").eq(drp.clk)
        m.submodules.clkprobe = clkprobe = DomainRenamer({"cfg": "dbg"})(
            ClockFreqProbe(clk_freq=DBG_FREQ, baud=BAUD_RATE, channels=(
                ("ss", None),
                ("rxprobe", None),
                ("uparprobe", None),
                ("ss", rx_d102),
                ("ss", tx_d102),
            )))
        pipe_flags = Signal(4)
        m.submodules += FFSynchronizer(
            Cat(adapter.power_down, adapter.tx_elec_idle,
                adapter.rx_elec_idle),
            pipe_flags, o_domain="dbg")
        m.d.comb += [
            clkprobe.flags.eq(pipe_flags),
            uart1.tx.o.eq(clkprobe.tx_o),
        ]
        rx1_unused = Signal()
        m.submodules += FFSynchronizer(uart1.rx.i, rx1_unused,
                                       o_domain="dbg")

        return m


# ======================================================================
# Build entry point
# ======================================================================

def generate_serdes_files():
    """Generate serdes.toml / serdes.csr for the selected BOOT_RATE.

    With BOOT_RATE="10G" the blob is byte-identical to the pinned,
    hardware-proven reference (verified at build time by comparison with
    the usb31-enum copy); the adapter then rate-switches to 5G itself.
    """
    serdes, _ = make_serdes()
    toml_path = HERE / "serdes.toml"
    csr_path = HERE / "serdes.csr"
    serdes.generate_csr(output_path=str(csr_path), toml_path=str(toml_path),
                        extra_writes=usb3_boot_writes(QUAD, LANE))
    print(f"Generated {toml_path.name} / {csr_path.name} ({BOOT_RATE} boot)")


def _setup_gowin_env(platform):
    import os
    os.environ.setdefault("LD_PRELOAD",
                          "/usr/lib/x86_64-linux-gnu/libfreetype.so.6")
    os.environ.setdefault("LD_LIBRARY_PATH",
                          str(Path(platform.gowin_path) / "IDE" / "lib"))
    gowin_bin = str(Path(platform.gowin_path) / "IDE" / "bin")
    if gowin_bin not in os.environ.get("PATH", ""):
        os.environ["PATH"] = gowin_bin + os.pathsep + os.environ["PATH"]


def build(do_program=False):
    generate_serdes_files()
    platform = DKUSBGW5AT60Platform()
    _setup_gowin_env(platform)
    platform.add_file("serdes.csr", (HERE / "serdes.csr").read_text())
    platform.build(LunaEnumTop(), name="luna_enum", build_dir="build",
                   do_program=do_program)


def flash():
    bitstream = HERE / "build" / "luna_enum.fs"
    if not bitstream.exists():
        sys.exit(f"no bitstream at {bitstream}; run `python top.py` first")
    cmd = ["openFPGALoader", "-c", "ft232", str(bitstream)]
    try:
        subprocess.check_call(cmd)
    except subprocess.CalledProcessError:
        subprocess.check_call(["sudo", "-n"] + cmd)


if __name__ == "__main__":
    if "serdes" in sys.argv:
        generate_serdes_files()
    elif "flash" in sys.argv:
        flash()
    else:
        build(do_program="program" in sys.argv)
